<a href="https://colab.research.google.com/github/nidhicodes4045/datascience442/blob/main/Project_Dataset_Cleaning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset

> #### Description

> The Food Access Research Atlas is a dataset that was developed by the United States Department of Agriculture's Economic Research Service (ERS) to understand and address the issue of limited access to healthy, affordable food across the US. This county-level dataset combines information from several sources, including the 2019 STARS directory of SNAP-authorized stores, a 2019 supermarket list, the 2010 Decennial Census, and the 2014-18 American Community Survey (ACS). By integrating data on store locations, demographics, and socioeconomic factors, the Atlas provides a comprehensive view of food access, enabling researchers to analyze the complex relationship between these factors and food insecurity within communities. Ryan Whitcomb, Joung Min Choi, and Bo Guan are associated with providing the dataset on CORGIS [Food Access](https://corgis-edu.github.io/corgis/csv/food_access/). It's possible they worked with the data after its initial creation by the ERS.

>The County Demographics dataset is a dataset originally compiled by the United States Census Bureau and made available through their QuickFacts tool.  It provides demographic information at the county level for the United States, designed to offer easy access to key population, business, and geographic statistics. This county-level dataset draws information from several Census Bureau sources, including the Decennial Census, the American Community Survey (ACS), the County Business Patterns (CBP), and the Population Estimates Program. By integrating data from these sources, the dataset provides a snapshot of key demographic indicators, enabling researchers to analyze various population characteristics. Ryan Whitcomb, Joung Min Choi, and Bo Guan are associated with providing the dataset on CORGIS [County Demographics](https://corgis-edu.github.io/corgis/csv/county_demographics/). It's possible they compiled or curated the data after its initial collection by the U.S. Census Bureau.

We have prepared a dataset that consists of a subset of these two CORGIS datasets. We will be referencing the data that we have prepared in our Github repository: ["food_df"]("https://raw.githubusercontent.com/nidhicodes4045/datascience442/refs/heads/main/Food_access_mod.csv") and ["county_df"]("https://raw.githubusercontent.com/nidhicodes4045/datascience442/refs/heads/main/county_demographics_mod.csv").

## Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
#!pip install us     #Just do it once
os.environ['DC_STATEHOOD'] = '1' # adds dc as a state
import seaborn as sns
import re

In [ ]:
import us

In [ ]:
print(os.getcwd())

/content

##Our Dataset initialization

In [ ]:
county_df = pd.read_csv("https://raw.githubusercontent.com/nidhicodes4045/datascience442/refs/heads/main/county_demographics_mod.csv")
food_df = pd.read_csv("https://raw.githubusercontent.com/nidhicodes4045/datascience442/refs/heads/main/Food_access_mod.csv")

##Dataframe info

###County df head and tail

In [ ]:
county_df.head()

,County,State,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,Ethnicities.Asian Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,Abbeville County,SC,22.4,19.8,4.7,15.6,81.7,1416,0.3,0.4,...,51.8,12507,91371,1450,543,689,317,1080,187,1211
1,Acadia Parish,LA,15.8,25.8,6.9,13.3,79.0,4533,0.4,0.3,...,94.3,52706,602739,4664,1516,2629,705,3734,388,4007
2,Accomack County,VA,24.6,20.7,5.6,19.5,81.5,2387,0.7,0.8,...,73.8,53568,348195,2997,802,1716,335,2560,212,2536
3,Ada County,ID,14.9,23.2,5.6,38.5,95.2,41464,0.8,2.7,...,372.8,763099,5766679,41789,14661,19409,3099,36701,3803,35132
4,Adair County,IA,23.0,21.8,5.6,18.5,94.2,609,0.3,0.5,...,13.5,,63002,914,304,499,0,861,185,679

In [ ]:
county_df.tail()

,County,State,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,Ethnicities.Asian Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
3134,Yuma County,AZ,19.3,25.1,7.1,15.0,73.3,9896,2.3,1.5,...,35.5,307540,1995974,10846,4298,4529,5749,4476,839,9265
3135,Yuma County,CO,18.7,27.4,7.5,21.8,88.6,1020,1,0.5,...,4.2,8501,125565,1492,391,797,45,1350,66,1278
3136,Zapata County,TX,13.2,33.1,8.6,11.6,61.9,1452,0.5,0.2,...,14.0,,75681,1964,818,1003,1680,235,181,1738
3137,Zavala County,TX,14.6,28.4,7.2,10.9,66.9,837,1.1,0.3,...,9.0,8808,45596,1232,486,674,1062,159,42,1178
3138,Ziebach County,SD,9.6,27.5,5.5,16.4,84.1,87,Unavailable,0.3,...,1.4,,15757,78,0,42,29,36,0,54

###Food df head and tail

In [ ]:
food_df.head()

,County,Population,State,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,Low Access Numbers.Children.1 Mile,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
0,Autauga County,54571,Alabama,455,20221,834,1045,222.0,0,9973,...,2307,0,37424.0,49497,5119,0,4393,5935.0,707,0
1,Baldwin County,182265,Alabama,2307,73180,1653,2178,32.0,0,30633,...,846,0,132442.0,165616,2308,0,21828,27241.0,390,0
2,Barbour County,27457,Alabama,3193,9820,545,742,201.0,0,3701,...,2440,0,NaN,23762,4643,0,2537,3348.0,629,0
3,Bibb County,22915,Alabama,2224,7953,312,441,0.0,0,4198,...,102,0,17560.0,20989,365,0,2262,2630.0,72,0
4,Blount County,57322,Alabama,489,21578,752,822,0.0,0,12575,...,0,0,50848.0,54933,0,0,7114,7810.0,0,0

In [ ]:
food_df.tail()

,County,Population,State,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,Low Access Numbers.Children.1 Mile,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
3137,Sweetwater County,43806,Wyoming,679,16475,284,372,18.0,13,6280,...,759,614,24036.0,36045,2548,2063,2358,3232.0,255,203
3138,Teton County,21294,Wyoming,271,8973,74,144,0.0,0,2853,...,383,181,15298.0,18354,1677,572,1867,2009.0,218,85
3139,Uinta County,21118,Wyoming,270,7668,175,283,9.0,0,3755,...,290,3,12250.0,17998,726,14,1078,NaN,97,3
3140,Washakie County,8533,Wyoming,140,3492,37,106,7.0,6,746,...,218,176,2869.0,4961,902,730,506,NaN,218,191
3141,Weston County,7208,Wyoming,313,3021,22,43,2.0,0,735,...,247,55,3659.0,5237,840,188,518,824.0,154,44

###county df info

In [ ]:
county_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3139 entries, 0 to 3138
Data columns (total 43 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   County                                                        3139 non-null   object
 1   State                                                         3139 non-null   object
 2   Age.Percent 65 and Older                                      3139 non-null   float64
 3   Age.Percent Under 18 Years                                    3139 non-null   object
 4   Age.Percent Under 5 Years                                     3139 non-null   object
 5   Education.Bachelor's Degree or Higher                         3139 non-null   float64
 6   Education.High School or Higher                               3139 non-null   float64
 7   Employment.Nonemployer Establishments                         3139 non-null   object
 8   Ethnicities.American Indian and Alaska Native Alone           3139 non-null   object
 9   Ethnicities.Asian Alone                                       3139 non-null   object
 10  Ethnicities.Black Alone                                       3139 non-null   object
 11  Ethnicities.Hispanic or Latino                                3139 non-null   float64
 12  Ethnicities.Native Hawaiian and Other Pacific Islander Alone  3139 non-null   object
 13  Ethnicities.Two or More Races                                 3139 non-null   object
 14  Ethnicities.White Alone                                       3139 non-null   float64
 15  Ethnicities.White Alone	 not Hispanic or Latino               3139 non-null   float64
 16  Housing.Homeownership Rate                                    3139 non-null   object
 17  Housing.Households                                            2900 non-null   float64
 18  Housing.Housing Units                                         3139 non-null   object
 19  Housing.Median Value of Owner-Occupied Units                  3139 non-null   object
 20  Housing.Persons per Household                                 3139 non-null   float64
 21  Income.Median Houseold Income                                 3139 non-null   int64
 22  Income.Per Capita Income                                      3139 non-null   int64
 23  Miscellaneous.Foreign Born                                    3139 non-null   float64
 24  Miscellaneous.Land Area                                       3139 non-null   float64
 25  Miscellaneous.Language Other than English at Home             3139 non-null   float64
 26  Miscellaneous.Living in Same House +1 Years                   3139 non-null   float64
 27  Miscellaneous.Manufacturers Shipments                         3139 non-null   object
 28  Miscellaneous.Mean Travel Time to Work                        3139 non-null   object
 29  Miscellaneous.Percent Female                                  3139 non-null   float64
 30  Miscellaneous.Veterans                                        3139 non-null   object
 31  Population.2020 Population                                    3139 non-null   int64
 32  Population.2010 Population                                    3139 non-null   int64
 33  Population.Population per Square Mile                         3139 non-null   float64
 34  Sales.Accommodation and Food Services Sales                   3139 non-null   object
 35  Sales.Retail Sales                                            3139 non-null   object
 36  Employment.Firms.Total                                        3139 non-null   int64
 37  Employment.Firms.Women-Owned                                  3139 non-null   int64
 38  Employment.Firms.Men-Owned                                    3139 non-null   int64
 39  Employment.Firms.Minority-Owned                               3139 non-null   object
 40  Employment.Firms.Nonminority-Owned                            3139 non-null   int64
 41  Employment.Firms.Veteran-Owned                                3139 non-null   int64
 42  Employment.Firms.Nonveteran-Owned                             3139 non-null   int64
dtypes: float64(14), int64(10), object(19)
memory usage: 1.0+ MB

###food df info

In [ ]:
food_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 25 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   County                                         3142 non-null   object
 1   Population                                     3142 non-null   int64
 2   State                                          3142 non-null   object
 3   Housing Data.Residing in Group Quarters        3142 non-null   int64
 4   Housing Data.Total Housing Units               3142 non-null   int64
 5   Vehicle Access.1 Mile                          3142 non-null   int64
 6   Vehicle Access.1/2 Mile                        3142 non-null   int64
 7   Vehicle Access.10 Miles                        2807 non-null   float64
 8   Vehicle Access.20 Miles                        3142 non-null   int64
 9   Low Access Numbers.Children.1 Mile             3142 non-null   int64
 10  Low Access Numbers.Children.1/2 Mile           3142 non-null   int64
 11  Low Access Numbers.Children.10 Miles           3142 non-null   int64
 12  Low Access Numbers.Children.20 Miles           3142 non-null   int64
 13  Low Access Numbers.Low Income People.1 Mile    3142 non-null   int64
 14  Low Access Numbers.Low Income People.1/2 Mile  3142 non-null   int64
 15  Low Access Numbers.Low Income People.10 Miles  3142 non-null   int64
 16  Low Access Numbers.Low Income People.20 Miles  3142 non-null   int64
 17  Low Access Numbers.People.1 Mile               2986 non-null   float64
 18  Low Access Numbers.People.1/2 Mile             3142 non-null   int64
 19  Low Access Numbers.People.10 Miles             3142 non-null   int64
 20  Low Access Numbers.People.20 Miles             3142 non-null   int64
 21  Low Access Numbers.Seniors.1 Mile              3142 non-null   int64
 22  Low Access Numbers.Seniors.1/2 Mile            2484 non-null   float64
 23  Low Access Numbers.Seniors.10 Miles            3142 non-null   int64
 24  Low Access Numbers.Seniors.20 Miles            3142 non-null   int64
dtypes: float64(3), int64(20), object(2)
memory usage: 613.8+ KB

###null count

In [ ]:
print(food_df.isnull().sum())

County                                             0
Population                                         0
State                                              0
Housing Data.Residing in Group Quarters            0
Housing Data.Total Housing Units                   0
Vehicle Access.1 Mile                              0
Vehicle Access.1/2 Mile                            0
Vehicle Access.10 Miles                          335
Vehicle Access.20 Miles                            0
Low Access Numbers.Children.1 Mile                 0
Low Access Numbers.Children.1/2 Mile               0
Low Access Numbers.Children.10 Miles               0
Low Access Numbers.Children.20 Miles               0
Low Access Numbers.Low Income People.1 Mile        0
Low Access Numbers.Low Income People.1/2 Mile      0
Low Access Numbers.Low Income People.10 Miles      0
Low Access Numbers.Low Income People.20 Miles      0
Low Access Numbers.People.1 Mile                 156
Low Access Numbers.People.1/2 Mile                 0
Low Access Numbers.People.10 Miles                 0
Low Access Numbers.People.20 Miles                 0
Low Access Numbers.Seniors.1 Mile                  0
Low Access Numbers.Seniors.1/2 Mile              658
Low Access Numbers.Seniors.10 Miles                0
Low Access Numbers.Seniors.20 Miles                0
dtype: int64


#Data Cleaning Step 1: Rectify structural misalignments
1. Check shape of the data – number of columns and rows  
2. Make sure the columns are named for convenience, follow the data dictionary
3. Do rows need to be named? Would default 0 order index work?

In [ ]:
county_df_shape = county_df.shape
print(county_df_shape)

(3139, 43)

In [ ]:
food_df_shape = food_df.shape
print(food_df_shape)

(3142, 25)

Food df has 3 more rows
county df has more cols

In [ ]:
#function to lowercase all text
def lowerandstriptext(text):
  newtext = re.sub(r"[\s\t]+", "", text)
  return newtext.lower().strip()

In [ ]:
#function to convert full state names to abbr
def convertstate(text):
  if us.states.lookup(text) is None:
    return "None"
  else:
    state = us.states.lookup(text).abbr
    statenew = re.sub(r"[\s\t]+", "", state)
    return statenew.lower().strip()

In [ ]:
#Apply the lowercase and strip functions to the State and County cols county df
county_df["County"] = county_df["County"].apply(lowerandstriptext)
county_df["State"] = county_df["State"].apply(lowerandstriptext)
county_df.head()

,County,State,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,Ethnicities.Asian Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,abbevillecounty,sc,22.4,19.8,4.7,15.6,81.7,1416,0.3,0.4,...,51.8,12507,91371,1450,543,689,317,1080,187,1211
1,acadiaparish,la,15.8,25.8,6.9,13.3,79.0,4533,0.4,0.3,...,94.3,52706,602739,4664,1516,2629,705,3734,388,4007
2,accomackcounty,va,24.6,20.7,5.6,19.5,81.5,2387,0.7,0.8,...,73.8,53568,348195,2997,802,1716,335,2560,212,2536
3,adacounty,id,14.9,23.2,5.6,38.5,95.2,41464,0.8,2.7,...,372.8,763099,5766679,41789,14661,19409,3099,36701,3803,35132
4,adaircounty,ia,23.0,21.8,5.6,18.5,94.2,609,0.3,0.5,...,13.5,,63002,914,304,499,0,861,185,679

In [ ]:
#Apply the preprocessing functions to food df
food_df["County"] = food_df["County"].apply(lowerandstriptext)
food_df["State"] = food_df["State"].apply(convertstate)
food_df.head()

,County,Population,State,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,Low Access Numbers.Children.1 Mile,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
0,autaugacounty,54571,al,455,20221,834,1045,222.0,0,9973,...,2307,0,37424.0,49497,5119,0,4393,5935.0,707,0
1,baldwincounty,182265,al,2307,73180,1653,2178,32.0,0,30633,...,846,0,132442.0,165616,2308,0,21828,27241.0,390,0
2,barbourcounty,27457,al,3193,9820,545,742,201.0,0,3701,...,2440,0,NaN,23762,4643,0,2537,3348.0,629,0
3,bibbcounty,22915,al,2224,7953,312,441,0.0,0,4198,...,102,0,17560.0,20989,365,0,2262,2630.0,72,0
4,blountcounty,57322,al,489,21578,752,822,0.0,0,12575,...,0,0,50848.0,54933,0,0,7114,7810.0,0,0

In [ ]:
#Verify if any 'Nones' exist before merging
check_state_food_df = (food_df['State'] == 'None').sum()
print("The number of 'None' in food_df: " + str(check_state_food_df))

The number of 'None' in food_df: 0

In [ ]:
#Insert merged columns at index 2 and 3 for county and food dfs respectively
county_df.insert(2, "mergedkeycol", county_df['County'] + county_df['State'])
food_df.insert(3, "mergedkeycol", food_df['County'] + food_df['State'])

In [ ]:
#Check county df
county_df.head()

,County,State,mergedkeycol,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,abbevillecounty,sc,abbevillecountysc,22.4,19.8,4.7,15.6,81.7,1416,0.3,...,51.8,12507,91371,1450,543,689,317,1080,187,1211
1,acadiaparish,la,acadiaparishla,15.8,25.8,6.9,13.3,79.0,4533,0.4,...,94.3,52706,602739,4664,1516,2629,705,3734,388,4007
2,accomackcounty,va,accomackcountyva,24.6,20.7,5.6,19.5,81.5,2387,0.7,...,73.8,53568,348195,2997,802,1716,335,2560,212,2536
3,adacounty,id,adacountyid,14.9,23.2,5.6,38.5,95.2,41464,0.8,...,372.8,763099,5766679,41789,14661,19409,3099,36701,3803,35132
4,adaircounty,ia,adaircountyia,23.0,21.8,5.6,18.5,94.2,609,0.3,...,13.5,,63002,914,304,499,0,861,185,679

In [ ]:
county_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3139 entries, 0 to 3138
Data columns (total 44 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   County                                                        3139 non-null   object
 1   State                                                         3139 non-null   object
 2   mergedkeycol                                                  3139 non-null   object
 3   Age.Percent 65 and Older                                      3139 non-null   float64
 4   Age.Percent Under 18 Years                                    3139 non-null   object
 5   Age.Percent Under 5 Years                                     3139 non-null   object
 6   Education.Bachelor's Degree or Higher                         3139 non-null   float64
 7   Education.High School or Higher                               3139 non-null   float64
 8   Employment.Nonemployer Establishments                         3139 non-null   object
 9   Ethnicities.American Indian and Alaska Native Alone           3139 non-null   object
 10  Ethnicities.Asian Alone                                       3139 non-null   object
 11  Ethnicities.Black Alone                                       3139 non-null   object
 12  Ethnicities.Hispanic or Latino                                3139 non-null   float64
 13  Ethnicities.Native Hawaiian and Other Pacific Islander Alone  3139 non-null   object
 14  Ethnicities.Two or More Races                                 3139 non-null   object
 15  Ethnicities.White Alone                                       3139 non-null   float64
 16  Ethnicities.White Alone	 not Hispanic or Latino               3139 non-null   float64
 17  Housing.Homeownership Rate                                    3139 non-null   object
 18  Housing.Households                                            2900 non-null   float64
 19  Housing.Housing Units                                         3139 non-null   object
 20  Housing.Median Value of Owner-Occupied Units                  3139 non-null   object
 21  Housing.Persons per Household                                 3139 non-null   float64
 22  Income.Median Houseold Income                                 3139 non-null   int64
 23  Income.Per Capita Income                                      3139 non-null   int64
 24  Miscellaneous.Foreign Born                                    3139 non-null   float64
 25  Miscellaneous.Land Area                                       3139 non-null   float64
 26  Miscellaneous.Language Other than English at Home             3139 non-null   float64
 27  Miscellaneous.Living in Same House +1 Years                   3139 non-null   float64
 28  Miscellaneous.Manufacturers Shipments                         3139 non-null   object
 29  Miscellaneous.Mean Travel Time to Work                        3139 non-null   object
 30  Miscellaneous.Percent Female                                  3139 non-null   float64
 31  Miscellaneous.Veterans                                        3139 non-null   object
 32  Population.2020 Population                                    3139 non-null   int64
 33  Population.2010 Population                                    3139 non-null   int64
 34  Population.Population per Square Mile                         3139 non-null   float64
 35  Sales.Accommodation and Food Services Sales                   3139 non-null   object
 36  Sales.Retail Sales                                            3139 non-null   object
 37  Employment.Firms.Total                                        3139 non-null   int64
 38  Employment.Firms.Women-Owned                                  3139 non-null   int64
 39  Employment.Firms.Men-Owned                                    3139 non-null   int64
 40  Employment.Firms.Minority-Owned                               3139 non-null   object
 41  Employment.Firms.Nonminority-Owned                            3139 non-null   int64
 42  Employment.Firms.Veteran-Owned                                3139 non-null   int64
 43  Employment.Firms.Nonveteran-Owned                             3139 non-null   int64
dtypes: float64(14), int64(10), object(20)
memory usage: 1.1+ MB

In [ ]:
#Check food df
food_df.head()

,County,Population,State,mergedkeycol,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
0,autaugacounty,54571,al,autaugacountyal,455,20221,834,1045,222.0,0,...,2307,0,37424.0,49497,5119,0,4393,5935.0,707,0
1,baldwincounty,182265,al,baldwincountyal,2307,73180,1653,2178,32.0,0,...,846,0,132442.0,165616,2308,0,21828,27241.0,390,0
2,barbourcounty,27457,al,barbourcountyal,3193,9820,545,742,201.0,0,...,2440,0,NaN,23762,4643,0,2537,3348.0,629,0
3,bibbcounty,22915,al,bibbcountyal,2224,7953,312,441,0.0,0,...,102,0,17560.0,20989,365,0,2262,2630.0,72,0
4,blountcounty,57322,al,blountcountyal,489,21578,752,822,0.0,0,...,0,0,50848.0,54933,0,0,7114,7810.0,0,0

In [ ]:
county_df.dtypes

County                                                           object
State                                                            object
mergedkeycol                                                     object
Age.Percent 65 and Older                                        float64
Age.Percent Under 18 Years                                       object
Age.Percent Under 5 Years                                        object
Education.Bachelor's Degree or Higher                           float64
Education.High School or Higher                                 float64
Employment.Nonemployer Establishments                            object
Ethnicities.American Indian and Alaska Native Alone              object
Ethnicities.Asian Alone                                          object
Ethnicities.Black Alone                                          object
Ethnicities.Hispanic or Latino                                  float64
Ethnicities.Native Hawaiian and Other Pacific Islander Alone     object
Ethnicities.Two or More Races                                    object
Ethnicities.White Alone                                         float64
Ethnicities.White Alone\t not Hispanic or Latino                float64
Housing.Homeownership Rate                                       object
Housing.Households                                              float64
Housing.Housing Units                                            object
Housing.Median Value of Owner-Occupied Units                     object
Housing.Persons per Household                                   float64
Income.Median Houseold Income                                     int64
Income.Per Capita Income                                          int64
Miscellaneous.Foreign Born                                      float64
Miscellaneous.Land Area                                         float64
Miscellaneous.Language Other than English at Home               float64
Miscellaneous.Living in Same House +1 Years                     float64
Miscellaneous.Manufacturers Shipments                            object
Miscellaneous.Mean Travel Time to Work                           object
Miscellaneous.Percent Female                                    float64
Miscellaneous.Veterans                                           object
Population.2020 Population                                        int64
Population.2010 Population                                        int64
Population.Population per Square Mile                           float64
Sales.Accommodation and Food Services Sales                      object
Sales.Retail Sales                                               object
Employment.Firms.Total                                            int64
Employment.Firms.Women-Owned                                      int64
Employment.Firms.Men-Owned                                        int64
Employment.Firms.Minority-Owned                                  object
Employment.Firms.Nonminority-Owned                                int64
Employment.Firms.Veteran-Owned                                    int64
Employment.Firms.Nonveteran-Owned                                 int64
dtype: object

In [ ]:
#Replaces all non-numeric values with missing values for all numeric columns
words = ['Age', 'Miscellaneous', 'Housing', 'Ethnicities', 'Employment', 'Sales']
numeric_cols =  county_df[[col for col in county_df.columns if any(word in col for word in words)]]
county_df[[col for col in county_df.columns if any(word in col for word in words)]] = numeric_cols.map(lambda x: pd.to_numeric(x, errors='coerce'))

In [ ]:
county_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3139 entries, 0 to 3138
Data columns (total 44 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   County                                                        3139 non-null   object
 1   State                                                         3139 non-null   object
 2   mergedkeycol                                                  3139 non-null   object
 3   Age.Percent 65 and Older                                      3139 non-null   float64
 4   Age.Percent Under 18 Years                                    3138 non-null   float64
 5   Age.Percent Under 5 Years                                     3138 non-null   float64
 6   Education.Bachelor's Degree or Higher                         3139 non-null   float64
 7   Education.High School or Higher                               3139 non-null   float64
 8   Employment.Nonemployer Establishments                         3098 non-null   float64
 9   Ethnicities.American Indian and Alaska Native Alone           3102 non-null   float64
 10  Ethnicities.Asian Alone                                       3132 non-null   float64
 11  Ethnicities.Black Alone                                       3131 non-null   float64
 12  Ethnicities.Hispanic or Latino                                3139 non-null   float64
 13  Ethnicities.Native Hawaiian and Other Pacific Islander Alone  2935 non-null   float64
 14  Ethnicities.Two or More Races                                 3137 non-null   float64
 15  Ethnicities.White Alone                                       3139 non-null   float64
 16  Ethnicities.White Alone	 not Hispanic or Latino               3139 non-null   float64
 17  Housing.Homeownership Rate                                    3138 non-null   float64
 18  Housing.Households                                            2900 non-null   float64
 19  Housing.Housing Units                                         3099 non-null   float64
 20  Housing.Median Value of Owner-Occupied Units                  3137 non-null   float64
 21  Housing.Persons per Household                                 3139 non-null   float64
 22  Income.Median Houseold Income                                 3139 non-null   int64
 23  Income.Per Capita Income                                      3139 non-null   int64
 24  Miscellaneous.Foreign Born                                    3139 non-null   float64
 25  Miscellaneous.Land Area                                       3139 non-null   float64
 26  Miscellaneous.Language Other than English at Home             3139 non-null   float64
 27  Miscellaneous.Living in Same House +1 Years                   3139 non-null   float64
 28  Miscellaneous.Manufacturers Shipments                         1945 non-null   float64
 29  Miscellaneous.Mean Travel Time to Work                        3138 non-null   float64
 30  Miscellaneous.Percent Female                                  3139 non-null   float64
 31  Miscellaneous.Veterans                                        3138 non-null   float64
 32  Population.2020 Population                                    3139 non-null   int64
 33  Population.2010 Population                                    3139 non-null   int64
 34  Population.Population per Square Mile                         3139 non-null   float64
 35  Sales.Accommodation and Food Services Sales                   2451 non-null   float64
 36  Sales.Retail Sales                                            3079 non-null   float64
 37  Employment.Firms.Total                                        3139 non-null   int64
 38  Employment.Firms.Women-Owned                                  3139 non-null   int64
 39  Employment.Firms.Men-Owned                                    3139 non-null   int64
 40  Employment.Firms.Minority-Owned                               3131 non-null   float64
 41  Employment.Firms.Nonminority-Owned                            3139 non-null   int64
 42  Employment.Firms.Veteran-Owned                                3139 non-null   int64
 43  Employment.Firms.Nonveteran-Owned                             3139 non-null   int64
dtypes: float64(31), int64(10), object(3)
memory usage: 1.1+ MB

In [ ]:
def export_dataframe_to_excel(df, file_path, sheet_name='Sheet1', index=False):
    """
    Exports a Pandas DataFrame to an Excel file.

    Args:
        df (pd.DataFrame): The DataFrame to export.
        file_path (str): The path to the Excel file.
        sheet_name (str, optional): The name of the sheet. Defaults to 'Sheet1'.
        index (bool, optional): Whether to include the DataFrame index in the Excel file. Defaults to False.
    """
    try:
        df.to_excel(file_path, sheet_name=sheet_name, index=index)
        print(f"DataFrame successfully exported to {file_path}")
    except Exception as e:
        print(f"Error exporting DataFrame: {e}")
# Export the DataFrame to an Excel file
export_dataframe_to_excel(county_df, 'county_df.xlsx', sheet_name='county_demographics')

DataFrame successfully exported to county_df.xlsx

In [ ]:
#Iterate through each column for county
for col in county_df.columns:
    # Calculate the percentage of missing values
    missing_percentage = county_df[col].isna().mean()

    if missing_percentage < 0.05:
        # Drop rows if missing data is below threshold
        county_df = county_df[county_df[col].notna()]
    else:
        # Replace missing values with median if above threshold
        median_value = county_df[col].median()
        county_df.fillna({col: median_value}, inplace=True)

In [ ]:
county_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2994 entries, 0 to 3137
Data columns (total 44 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   County                                                        2994 non-null   object
 1   State                                                         2994 non-null   object
 2   mergedkeycol                                                  2994 non-null   object
 3   Age.Percent 65 and Older                                      2994 non-null   float64
 4   Age.Percent Under 18 Years                                    2994 non-null   float64
 5   Age.Percent Under 5 Years                                     2994 non-null   float64
 6   Education.Bachelor's Degree or Higher                         2994 non-null   float64
 7   Education.High School or Higher                               2994 non-null   float64
 8   Employment.Nonemployer Establishments                         2994 non-null   float64
 9   Ethnicities.American Indian and Alaska Native Alone           2994 non-null   float64
 10  Ethnicities.Asian Alone                                       2994 non-null   float64
 11  Ethnicities.Black Alone                                       2994 non-null   float64
 12  Ethnicities.Hispanic or Latino                                2994 non-null   float64
 13  Ethnicities.Native Hawaiian and Other Pacific Islander Alone  2994 non-null   float64
 14  Ethnicities.Two or More Races                                 2994 non-null   float64
 15  Ethnicities.White Alone                                       2994 non-null   float64
 16  Ethnicities.White Alone	 not Hispanic or Latino               2994 non-null   float64
 17  Housing.Homeownership Rate                                    2994 non-null   float64
 18  Housing.Households                                            2994 non-null   float64
 19  Housing.Housing Units                                         2994 non-null   float64
 20  Housing.Median Value of Owner-Occupied Units                  2994 non-null   float64
 21  Housing.Persons per Household                                 2994 non-null   float64
 22  Income.Median Houseold Income                                 2994 non-null   int64
 23  Income.Per Capita Income                                      2994 non-null   int64
 24  Miscellaneous.Foreign Born                                    2994 non-null   float64
 25  Miscellaneous.Land Area                                       2994 non-null   float64
 26  Miscellaneous.Language Other than English at Home             2994 non-null   float64
 27  Miscellaneous.Living in Same House +1 Years                   2994 non-null   float64
 28  Miscellaneous.Manufacturers Shipments                         2994 non-null   float64
 29  Miscellaneous.Mean Travel Time to Work                        2994 non-null   float64
 30  Miscellaneous.Percent Female                                  2994 non-null   float64
 31  Miscellaneous.Veterans                                        2994 non-null   float64
 32  Population.2020 Population                                    2994 non-null   int64
 33  Population.2010 Population                                    2994 non-null   int64
 34  Population.Population per Square Mile                         2994 non-null   float64
 35  Sales.Accommodation and Food Services Sales                   2994 non-null   float64
 36  Sales.Retail Sales                                            2994 non-null   float64
 37  Employment.Firms.Total                                        2994 non-null   int64
 38  Employment.Firms.Women-Owned                                  2994 non-null   int64
 39  Employment.Firms.Men-Owned                                    2994 non-null   int64
 40  Employment.Firms.Minority-Owned                               2994 non-null   float64
 41  Employment.Firms.Nonminority-Owned                            2994 non-null   int64
 42  Employment.Firms.Veteran-Owned                                2994 non-null   int64
 43  Employment.Firms.Nonveteran-Owned                             2994 non-null   int64
dtypes: float64(31), int64(10), object(3)
memory usage: 1.0+ MB

In [ ]:
#check if there are any missing values
county_df.isna().sum()

County                                                          0
State                                                           0
mergedkeycol                                                    0
Age.Percent 65 and Older                                        0
Age.Percent Under 18 Years                                      0
Age.Percent Under 5 Years                                       0
Education.Bachelor's Degree or Higher                           0
Education.High School or Higher                                 0
Employment.Nonemployer Establishments                           0
Ethnicities.American Indian and Alaska Native Alone             0
Ethnicities.Asian Alone                                         0
Ethnicities.Black Alone                                         0
Ethnicities.Hispanic or Latino                                  0
Ethnicities.Native Hawaiian and Other Pacific Islander Alone    0
Ethnicities.Two or More Races                                   0
Ethnicities.White Alone                                         0
Ethnicities.White Alone\t not Hispanic or Latino                0
Housing.Homeownership Rate                                      0
Housing.Households                                              0
Housing.Housing Units                                           0
Housing.Median Value of Owner-Occupied Units                    0
Housing.Persons per Household                                   0
Income.Median Houseold Income                                   0
Income.Per Capita Income                                        0
Miscellaneous.Foreign Born                                      0
Miscellaneous.Land Area                                         0
Miscellaneous.Language Other than English at Home               0
Miscellaneous.Living in Same House +1 Years                     0
Miscellaneous.Manufacturers Shipments                           0
Miscellaneous.Mean Travel Time to Work                          0
Miscellaneous.Percent Female                                    0
Miscellaneous.Veterans                                          0
Population.2020 Population                                      0
Population.2010 Population                                      0
Population.Population per Square Mile                           0
Sales.Accommodation and Food Services Sales                     0
Sales.Retail Sales                                              0
Employment.Firms.Total                                          0
Employment.Firms.Women-Owned                                    0
Employment.Firms.Men-Owned                                      0
Employment.Firms.Minority-Owned                                 0
Employment.Firms.Nonminority-Owned                              0
Employment.Firms.Veteran-Owned                                  0
Employment.Firms.Nonveteran-Owned                               0
dtype: int64

In [ ]:
county_df.head()

,County,State,mergedkeycol,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,abbevillecounty,sc,abbevillecountysc,22.4,19.8,4.7,15.6,81.7,1416.0,0.3,...,51.8,12507.0,91371.0,1450,543,689,317.0,1080,187,1211
1,acadiaparish,la,acadiaparishla,15.8,25.8,6.9,13.3,79.0,4533.0,0.4,...,94.3,52706.0,602739.0,4664,1516,2629,705.0,3734,388,4007
2,accomackcounty,va,accomackcountyva,24.6,20.7,5.6,19.5,81.5,2387.0,0.7,...,73.8,53568.0,348195.0,2997,802,1716,335.0,2560,212,2536
3,adacounty,id,adacountyid,14.9,23.2,5.6,38.5,95.2,41464.0,0.8,...,372.8,763099.0,5766679.0,41789,14661,19409,3099.0,36701,3803,35132
4,adaircounty,ia,adaircountyia,23.0,21.8,5.6,18.5,94.2,609.0,0.3,...,13.5,44317.0,63002.0,914,304,499,0.0,861,185,679

##Cleaning Food_df

###Checking DataTypes

In [ ]:
food_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 26 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   County                                         3142 non-null   object
 1   Population                                     3142 non-null   int64
 2   State                                          3142 non-null   object
 3   mergedkeycol                                   3142 non-null   object
 4   Housing Data.Residing in Group Quarters        3142 non-null   int64
 5   Housing Data.Total Housing Units               3142 non-null   int64
 6   Vehicle Access.1 Mile                          3142 non-null   int64
 7   Vehicle Access.1/2 Mile                        3142 non-null   int64
 8   Vehicle Access.10 Miles                        2807 non-null   float64
 9   Vehicle Access.20 Miles                        3142 non-null   int64
 10  Low Access Numbers.Children.1 Mile             3142 non-null   int64
 11  Low Access Numbers.Children.1/2 Mile           3142 non-null   int64
 12  Low Access Numbers.Children.10 Miles           3142 non-null   int64
 13  Low Access Numbers.Children.20 Miles           3142 non-null   int64
 14  Low Access Numbers.Low Income People.1 Mile    3142 non-null   int64
 15  Low Access Numbers.Low Income People.1/2 Mile  3142 non-null   int64
 16  Low Access Numbers.Low Income People.10 Miles  3142 non-null   int64
 17  Low Access Numbers.Low Income People.20 Miles  3142 non-null   int64
 18  Low Access Numbers.People.1 Mile               2986 non-null   float64
 19  Low Access Numbers.People.1/2 Mile             3142 non-null   int64
 20  Low Access Numbers.People.10 Miles             3142 non-null   int64
 21  Low Access Numbers.People.20 Miles             3142 non-null   int64
 22  Low Access Numbers.Seniors.1 Mile              3142 non-null   int64
 23  Low Access Numbers.Seniors.1/2 Mile            2484 non-null   float64
 24  Low Access Numbers.Seniors.10 Miles            3142 non-null   int64
 25  Low Access Numbers.Seniors.20 Miles            3142 non-null   int64
dtypes: float64(3), int64(20), object(3)
memory usage: 638.3+ KB

###Checking for Null Values

In [ ]:
for col in food_df.columns[4:26]:
    print(f"'{col}': {food_df[col].isnull().sum()}")

'Housing Data.Residing in Group Quarters': 0
'Housing Data.Total Housing Units': 0
'Vehicle Access.1 Mile': 0
'Vehicle Access.1/2 Mile': 0
'Vehicle Access.10 Miles': 335
'Vehicle Access.20 Miles': 0
'Low Access Numbers.Children.1 Mile': 0
'Low Access Numbers.Children.1/2 Mile': 0
'Low Access Numbers.Children.10 Miles': 0
'Low Access Numbers.Children.20 Miles': 0
'Low Access Numbers.Low Income People.1 Mile': 0
'Low Access Numbers.Low Income People.1/2 Mile': 0
'Low Access Numbers.Low Income People.10 Miles': 0
'Low Access Numbers.Low Income People.20 Miles': 0
'Low Access Numbers.People.1 Mile': 156
'Low Access Numbers.People.1/2 Mile': 0
'Low Access Numbers.People.10 Miles': 0
'Low Access Numbers.People.20 Miles': 0
'Low Access Numbers.Seniors.1 Mile': 0
'Low Access Numbers.Seniors.1/2 Mile': 658
'Low Access Numbers.Seniors.10 Miles': 0
'Low Access Numbers.Seniors.20 Miles': 0

In [ ]:
pd.isna(food_df['Vehicle Access.10 Miles'][19])

True

In [ ]:
pd.isna(food_df['Low Access Numbers.People.1 Mile'][2])

True

In [ ]:
for col in food_df.columns[4:26]:
    # Count the occurrences of NaN values in the column
    nan_count = food_df[col].isnull().sum()

    # Print the column name and the count of NaN values
    print(f"'{col}': {nan_count}")

'Housing Data.Residing in Group Quarters': 0
'Housing Data.Total Housing Units': 0
'Vehicle Access.1 Mile': 0
'Vehicle Access.1/2 Mile': 0
'Vehicle Access.10 Miles': 335
'Vehicle Access.20 Miles': 0
'Low Access Numbers.Children.1 Mile': 0
'Low Access Numbers.Children.1/2 Mile': 0
'Low Access Numbers.Children.10 Miles': 0
'Low Access Numbers.Children.20 Miles': 0
'Low Access Numbers.Low Income People.1 Mile': 0
'Low Access Numbers.Low Income People.1/2 Mile': 0
'Low Access Numbers.Low Income People.10 Miles': 0
'Low Access Numbers.Low Income People.20 Miles': 0
'Low Access Numbers.People.1 Mile': 156
'Low Access Numbers.People.1/2 Mile': 0
'Low Access Numbers.People.10 Miles': 0
'Low Access Numbers.People.20 Miles': 0
'Low Access Numbers.Seniors.1 Mile': 0
'Low Access Numbers.Seniors.1/2 Mile': 658
'Low Access Numbers.Seniors.10 Miles': 0
'Low Access Numbers.Seniors.20 Miles': 0

###TRIAL READCSV ISSUE

In [ ]:
mode_food_df = pd.read_csv("https://raw.githubusercontent.com/nidhicodes4045/datascience442/refs/heads/main/Food_access_mod.csv", dtype=str, keep_default_na=False)

In [ ]:
from IPython.display import display

# Checking different types of null representations
null_counts = {
    "Explicit NaN (pd.isna)": mode_food_df.applymap(lambda x: pd.isna(x)).sum(),
    "Empty Strings ('')": (mode_food_df == "").sum(),
    "Whitespace Strings": (mode_food_df.applymap(lambda x: x.strip() if isinstance(x, str) else x) == "").sum(),
    "Explicit 'N/A' Strings": (mode_food_df.applymap(lambda x: x.lower() if isinstance(x, str) else x) == "n/a").sum(),
    "Explicit 'NULL' Strings": (mode_food_df.applymap(lambda x: x.lower() if isinstance(x, str) else x) == "null").sum()
}

# Combine results into a DataFrame
null_summary = pd.DataFrame(null_counts)
# Show the DataFrame
display(null_summary)

<ipython-input-485-9f05aeb7ef44>:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  "Explicit NaN (pd.isna)": mode_food_df.applymap(lambda x: pd.isna(x)).sum(),
<ipython-input-485-9f05aeb7ef44>:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  "Whitespace Strings": (mode_food_df.applymap(lambda x: x.strip() if isinstance(x, str) else x) == "").sum(),
<ipython-input-485-9f05aeb7ef44>:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  "Explicit 'N/A' Strings": (mode_food_df.applymap(lambda x: x.lower() if isinstance(x, str) else x) == "n/a").sum(),
<ipython-input-485-9f05aeb7ef44>:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  "Explicit 'NULL' Strings": (mode_food_df.applymap(lambda x: x.lower() if isinstance(x, str) else x) == "null").sum()

,Explicit NaN (pd.isna),Empty Strings (''),Whitespace Strings,Explicit 'N/A' Strings,Explicit 'NULL' Strings
County,0,0,0,0,0
Population,0,0,0,0,0
State,0,0,0,0,0
Housing Data.Residing in Group Quarters,0,0,0,0,0
Housing Data.Total Housing Units,0,0,0,0,0
Vehicle Access.1 Mile,0,0,0,0,0
Vehicle Access.1/2 Mile,0,0,0,0,0
Vehicle Access.10 Miles,0,335,335,0,0
Vehicle Access.20 Miles,0,0,0,0,0
Low Access Numbers.Children.1 Mile,0,0,0,0,0
Low Access Numbers.Children.1/2 Mile,0,0,0,0,0
Low Access Numbers.Children.10 Miles,0,0,0,0,0
Low Access Numbers.Children.20 Miles,0,0,0,0,0
Low Access Numbers.Low Income People.1 Mile,0,0,0,0,0
Low Access Numbers.Low Income People.1/2 Mile,0,0,0,0,0
Low Access Numbers.Low Income People.10 Miles,0,0,0,0,0
Low Access Numbers.Low Income People.20 Miles,0,0,0,0,0
Low Access Numbers.People.1 Mile,0,0,0,156,0
Low Access Numbers.People.1/2 Mile,0,0,0,0,0
Low Access Numbers.People.10 Miles,0,0,0,0,0
Low Access Numbers.People.20 Miles,0,0,0,0,0
Low Access Numbers.Seniors.1 Mile,0,0,0,0,0
Low Access Numbers.Seniors.1/2 Mile,0,0,0,658,0
Low Access Numbers.Seniors.10 Miles,0,0,0,0,0
Low Access Numbers.Seniors.20 Miles,0,0,0,0,0

In [ ]:
mode_food_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 25 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   County                                         3142 non-null   object
 1   Population                                     3142 non-null   object
 2   State                                          3142 non-null   object
 3   Housing Data.Residing in Group Quarters        3142 non-null   object
 4   Housing Data.Total Housing Units               3142 non-null   object
 5   Vehicle Access.1 Mile                          3142 non-null   object
 6   Vehicle Access.1/2 Mile                        3142 non-null   object
 7   Vehicle Access.10 Miles                        3142 non-null   object
 8   Vehicle Access.20 Miles                        3142 non-null   object
 9   Low Access Numbers.Children.1 Mile             3142 non-null   object
 10  Low Access Numbers.Children.1/2 Mile           3142 non-null   object
 11  Low Access Numbers.Children.10 Miles           3142 non-null   object
 12  Low Access Numbers.Children.20 Miles           3142 non-null   object
 13  Low Access Numbers.Low Income People.1 Mile    3142 non-null   object
 14  Low Access Numbers.Low Income People.1/2 Mile  3142 non-null   object
 15  Low Access Numbers.Low Income People.10 Miles  3142 non-null   object
 16  Low Access Numbers.Low Income People.20 Miles  3142 non-null   object
 17  Low Access Numbers.People.1 Mile               3142 non-null   object
 18  Low Access Numbers.People.1/2 Mile             3142 non-null   object
 19  Low Access Numbers.People.10 Miles             3142 non-null   object
 20  Low Access Numbers.People.20 Miles             3142 non-null   object
 21  Low Access Numbers.Seniors.1 Mile              3142 non-null   object
 22  Low Access Numbers.Seniors.1/2 Mile            3142 non-null   object
 23  Low Access Numbers.Seniors.10 Miles            3142 non-null   object
 24  Low Access Numbers.Seniors.20 Miles            3142 non-null   object
dtypes: object(25)
memory usage: 613.8+ KB

In [ ]:
# Convert columns 4-25 (except 8, 18, and 23) to appropriate numerical types
cols_to_convert = [mode_food_df.columns[i] for i in range(3, 25) if i not in [7, 17, 22]]

# Convert to float since some numeric values may have decimals
mode_food_df[cols_to_convert] = mode_food_df[cols_to_convert].apply(pd.to_numeric, errors='coerce')

# Display the updated data types
mode_food_df.dtypes

County                                           object
Population                                       object
State                                            object
Housing Data.Residing in Group Quarters           int64
Housing Data.Total Housing Units                  int64
Vehicle Access.1 Mile                             int64
Vehicle Access.1/2 Mile                           int64
Vehicle Access.10 Miles                          object
Vehicle Access.20 Miles                           int64
Low Access Numbers.Children.1 Mile                int64
Low Access Numbers.Children.1/2 Mile              int64
Low Access Numbers.Children.10 Miles              int64
Low Access Numbers.Children.20 Miles              int64
Low Access Numbers.Low Income People.1 Mile       int64
Low Access Numbers.Low Income People.1/2 Mile     int64
Low Access Numbers.Low Income People.10 Miles     int64
Low Access Numbers.Low Income People.20 Miles     int64
Low Access Numbers.People.1 Mile                 object
Low Access Numbers.People.1/2 Mile                int64
Low Access Numbers.People.10 Miles                int64
Low Access Numbers.People.20 Miles                int64
Low Access Numbers.Seniors.1 Mile                 int64
Low Access Numbers.Seniors.1/2 Mile              object
Low Access Numbers.Seniors.10 Miles               int64
Low Access Numbers.Seniors.20 Miles               int64
dtype: object

## Summarize Missing value columns with temp df

In [ ]:
df_temp = mode_food_df.copy()
missing_cols = [mode_food_df.columns[7], mode_food_df.columns[17], mode_food_df.columns[22]]
df_temp[missing_cols] = df_temp[missing_cols].replace(["", " ", "N/A", "n/a", "NULL", "null"], None)
df_temp[missing_cols] = df_temp[missing_cols].apply(pd.to_numeric, errors='coerce').fillna(0)
summary_stats = df_temp[missing_cols].describe()
from IPython.display import display
display(summary_stats)

,Vehicle Access.10 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.Seniors.1/2 Mile
count,3142.000000,3142.000000,3142.000000
mean,27.729472,37205.573838,7162.901018
std,78.577763,64074.586653,17148.344674
min,0.000000,0.000000,0.000000
25%,0.000000,6282.500000,408.250000
50%,7.000000,16444.500000,2416.000000
75%,30.000000,39954.500000,6152.250000
max,1826.000000,903299.000000,319028.000000

#Analysis of the Summary

##Column: Vehicle Access.10 Miles (Column 7)

- Mean: 27.73
- Median (50%): 7.0
- Min: 0, Max: 1826
- Skewed distribution (high max value compared to median)
- Best Replacement: Median (7.0) (since mean is influenced by extreme values)

##Column: Low Access Numbers.People.1 Mile (Column 17)

- Mean: 37,205
- Median (50%): 16,444
- Min: 0, Max: 903,299
- Highly skewed (huge gap between min, median, and max)
- Best Replacement: Median (16,444.5) (again, to avoid extreme values pulling the mean)

##Column: Low Access Numbers.Seniors.1/2 Mile (Column 22)

- Mean: 7,162
- Median (50%): 2,416
- Min: 0, Max: 319,028
- Highly skewed (huge max value)
- Best Replacement: Median (2,416.0)

#Final Replacement Approach

- Replace missing values in Vehicle Access.10 Miles with 7.0
- Replace missing values in Low Access Numbers.People.1 Mile with 16,444.5
- Replace missing values in Low Access Numbers.Seniors.1/2 Mile with 2,416.

In [ ]:
# Define replacement values based on median
replacement_values = {
    mode_food_df.columns[7]: 7.0,          # Vehicle Access.10 Miles
    mode_food_df.columns[17]: 16444.5,     # Low Access Numbers.People.1 Mile
    mode_food_df.columns[22]: 2416.0       # Low Access Numbers.Seniors.1/2 Mile
}
columns_to_replace = list(replacement_values.keys())

# Normalize missing values
mode_food_df[columns_to_replace] = mode_food_df[columns_to_replace].replace(["", " ", "N/A", "n/a", "NULL", "null"], None)

# Convert to numeric and fill missing values
mode_food_df[columns_to_replace] = mode_food_df[columns_to_replace].apply(pd.to_numeric, errors='coerce').fillna(replacement_values)

# Verify the changes
from IPython.display import display
display(mode_food_df[replacement_values.keys()].describe())

,Vehicle Access.10 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.Seniors.1/2 Mile
count,3142.000000,3142.000000,3142.000000
mean,28.475812,38022.041693,7668.861553
std,78.343661,63698.844970,16964.133907
min,0.000000,0.000000,12.000000
25%,2.000000,7762.750000,2042.000000
50%,7.000000,16445.750000,2417.000000
75%,30.000000,39954.500000,6152.250000
max,1826.000000,903299.000000,319028.000000

In [ ]:
mode_food_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 25 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   County                                         3142 non-null   object
 1   Population                                     3142 non-null   object
 2   State                                          3142 non-null   object
 3   Housing Data.Residing in Group Quarters        3142 non-null   int64
 4   Housing Data.Total Housing Units               3142 non-null   int64
 5   Vehicle Access.1 Mile                          3142 non-null   int64
 6   Vehicle Access.1/2 Mile                        3142 non-null   int64
 7   Vehicle Access.10 Miles                        3142 non-null   float64
 8   Vehicle Access.20 Miles                        3142 non-null   int64
 9   Low Access Numbers.Children.1 Mile             3142 non-null   int64
 10  Low Access Numbers.Children.1/2 Mile           3142 non-null   int64
 11  Low Access Numbers.Children.10 Miles           3142 non-null   int64
 12  Low Access Numbers.Children.20 Miles           3142 non-null   int64
 13  Low Access Numbers.Low Income People.1 Mile    3142 non-null   int64
 14  Low Access Numbers.Low Income People.1/2 Mile  3142 non-null   int64
 15  Low Access Numbers.Low Income People.10 Miles  3142 non-null   int64
 16  Low Access Numbers.Low Income People.20 Miles  3142 non-null   int64
 17  Low Access Numbers.People.1 Mile               3142 non-null   float64
 18  Low Access Numbers.People.1/2 Mile             3142 non-null   int64
 19  Low Access Numbers.People.10 Miles             3142 non-null   int64
 20  Low Access Numbers.People.20 Miles             3142 non-null   int64
 21  Low Access Numbers.Seniors.1 Mile              3142 non-null   int64
 22  Low Access Numbers.Seniors.1/2 Mile            3142 non-null   float64
 23  Low Access Numbers.Seniors.10 Miles            3142 non-null   int64
 24  Low Access Numbers.Seniors.20 Miles            3142 non-null   int64
dtypes: float64(3), int64(19), object(3)
memory usage: 613.8+ KB

In [ ]:
mode_food_df['Low Access Numbers.People.1 Mile'][2]

16444.5

In [ ]:
mode_food_df['Vehicle Access.10 Miles'][19]

7.0

In [ ]:
mode_food_df['Low Access Numbers.Seniors.1/2 Mile'][3139]

2416.0

In [ ]:
mode_food_df.head()

,County,Population,State,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,Low Access Numbers.Children.1 Mile,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
0,Autauga County,54571,Alabama,455,20221,834,1045,222.0,0,9973,...,2307,0,37424.0,49497,5119,0,4393,5935.0,707,0
1,Baldwin County,182265,Alabama,2307,73180,1653,2178,32.0,0,30633,...,846,0,132442.0,165616,2308,0,21828,27241.0,390,0
2,Barbour County,27457,Alabama,3193,9820,545,742,201.0,0,3701,...,2440,0,16444.5,23762,4643,0,2537,3348.0,629,0
3,Bibb County,22915,Alabama,2224,7953,312,441,0.0,0,4198,...,102,0,17560.0,20989,365,0,2262,2630.0,72,0
4,Blount County,57322,Alabama,489,21578,752,822,0.0,0,12575,...,0,0,50848.0,54933,0,0,7114,7810.0,0,0

#Fixing primary key for the cleaned food dataframe (mode_food_df)

In [ ]:
#Apply the lowercase and strip functions to the State and County cols county df
#Apply the preprocessing functions to food df
mode_food_df["County"] = mode_food_df["County"].apply(lowerandstriptext)
mode_food_df["State"] = mode_food_df["State"].apply(convertstate)
mode_food_df.head()

,County,Population,State,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,Low Access Numbers.Children.1 Mile,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
0,autaugacounty,54571,al,455,20221,834,1045,222.0,0,9973,...,2307,0,37424.0,49497,5119,0,4393,5935.0,707,0
1,baldwincounty,182265,al,2307,73180,1653,2178,32.0,0,30633,...,846,0,132442.0,165616,2308,0,21828,27241.0,390,0
2,barbourcounty,27457,al,3193,9820,545,742,201.0,0,3701,...,2440,0,16444.5,23762,4643,0,2537,3348.0,629,0
3,bibbcounty,22915,al,2224,7953,312,441,0.0,0,4198,...,102,0,17560.0,20989,365,0,2262,2630.0,72,0
4,blountcounty,57322,al,489,21578,752,822,0.0,0,12575,...,0,0,50848.0,54933,0,0,7114,7810.0,0,0

In [ ]:
#Verify if any 'Nones' exist before merging
check_state_mode_food_df = (mode_food_df['State'] == 'None').sum()
print("The number of 'None' in mode_food_df: " + str(check_state_mode_food_df))

The number of 'None' in mode_food_df: 0

In [ ]:
#Insert merged columns at index 2 and 3 for county and food dfs respectively
mode_food_df.insert(3, "mergedkeycol", mode_food_df['County'] + mode_food_df['State'])

In [ ]:
mode_food_df.head()

,County,Population,State,mergedkeycol,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,...,Low Access Numbers.Low Income People.10 Miles,Low Access Numbers.Low Income People.20 Miles,Low Access Numbers.People.1 Mile,Low Access Numbers.People.1/2 Mile,Low Access Numbers.People.10 Miles,Low Access Numbers.People.20 Miles,Low Access Numbers.Seniors.1 Mile,Low Access Numbers.Seniors.1/2 Mile,Low Access Numbers.Seniors.10 Miles,Low Access Numbers.Seniors.20 Miles
0,autaugacounty,54571,al,autaugacountyal,455,20221,834,1045,222.0,0,...,2307,0,37424.0,49497,5119,0,4393,5935.0,707,0
1,baldwincounty,182265,al,baldwincountyal,2307,73180,1653,2178,32.0,0,...,846,0,132442.0,165616,2308,0,21828,27241.0,390,0
2,barbourcounty,27457,al,barbourcountyal,3193,9820,545,742,201.0,0,...,2440,0,16444.5,23762,4643,0,2537,3348.0,629,0
3,bibbcounty,22915,al,bibbcountyal,2224,7953,312,441,0.0,0,...,102,0,17560.0,20989,365,0,2262,2630.0,72,0
4,blountcounty,57322,al,blountcountyal,489,21578,752,822,0.0,0,...,0,0,50848.0,54933,0,0,7114,7810.0,0,0

In [ ]:
county_df.head()

,County,State,mergedkeycol,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,abbevillecounty,sc,abbevillecountysc,22.4,19.8,4.7,15.6,81.7,1416.0,0.3,...,51.8,12507.0,91371.0,1450,543,689,317.0,1080,187,1211
1,acadiaparish,la,acadiaparishla,15.8,25.8,6.9,13.3,79.0,4533.0,0.4,...,94.3,52706.0,602739.0,4664,1516,2629,705.0,3734,388,4007
2,accomackcounty,va,accomackcountyva,24.6,20.7,5.6,19.5,81.5,2387.0,0.7,...,73.8,53568.0,348195.0,2997,802,1716,335.0,2560,212,2536
3,adacounty,id,adacountyid,14.9,23.2,5.6,38.5,95.2,41464.0,0.8,...,372.8,763099.0,5766679.0,41789,14661,19409,3099.0,36701,3803,35132
4,adaircounty,ia,adaircountyia,23.0,21.8,5.6,18.5,94.2,609.0,0.3,...,13.5,44317.0,63002.0,914,304,499,0.0,861,185,679

In [ ]:
mode_food_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 26 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   County                                         3142 non-null   object
 1   Population                                     3142 non-null   object
 2   State                                          3142 non-null   object
 3   mergedkeycol                                   3142 non-null   object
 4   Housing Data.Residing in Group Quarters        3142 non-null   int64
 5   Housing Data.Total Housing Units               3142 non-null   int64
 6   Vehicle Access.1 Mile                          3142 non-null   int64
 7   Vehicle Access.1/2 Mile                        3142 non-null   int64
 8   Vehicle Access.10 Miles                        3142 non-null   float64
 9   Vehicle Access.20 Miles                        3142 non-null   int64
 10  Low Access Numbers.Children.1 Mile             3142 non-null   int64
 11  Low Access Numbers.Children.1/2 Mile           3142 non-null   int64
 12  Low Access Numbers.Children.10 Miles           3142 non-null   int64
 13  Low Access Numbers.Children.20 Miles           3142 non-null   int64
 14  Low Access Numbers.Low Income People.1 Mile    3142 non-null   int64
 15  Low Access Numbers.Low Income People.1/2 Mile  3142 non-null   int64
 16  Low Access Numbers.Low Income People.10 Miles  3142 non-null   int64
 17  Low Access Numbers.Low Income People.20 Miles  3142 non-null   int64
 18  Low Access Numbers.People.1 Mile               3142 non-null   float64
 19  Low Access Numbers.People.1/2 Mile             3142 non-null   int64
 20  Low Access Numbers.People.10 Miles             3142 non-null   int64
 21  Low Access Numbers.People.20 Miles             3142 non-null   int64
 22  Low Access Numbers.Seniors.1 Mile              3142 non-null   int64
 23  Low Access Numbers.Seniors.1/2 Mile            3142 non-null   float64
 24  Low Access Numbers.Seniors.10 Miles            3142 non-null   int64
 25  Low Access Numbers.Seniors.20 Miles            3142 non-null   int64
dtypes: float64(3), int64(19), object(4)
memory usage: 638.3+ KB

In [ ]:
county_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2994 entries, 0 to 3137
Data columns (total 44 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   County                                                        2994 non-null   object
 1   State                                                         2994 non-null   object
 2   mergedkeycol                                                  2994 non-null   object
 3   Age.Percent 65 and Older                                      2994 non-null   float64
 4   Age.Percent Under 18 Years                                    2994 non-null   float64
 5   Age.Percent Under 5 Years                                     2994 non-null   float64
 6   Education.Bachelor's Degree or Higher                         2994 non-null   float64
 7   Education.High School or Higher                               2994 non-null   float64
 8   Employment.Nonemployer Establishments                         2994 non-null   float64
 9   Ethnicities.American Indian and Alaska Native Alone           2994 non-null   float64
 10  Ethnicities.Asian Alone                                       2994 non-null   float64
 11  Ethnicities.Black Alone                                       2994 non-null   float64
 12  Ethnicities.Hispanic or Latino                                2994 non-null   float64
 13  Ethnicities.Native Hawaiian and Other Pacific Islander Alone  2994 non-null   float64
 14  Ethnicities.Two or More Races                                 2994 non-null   float64
 15  Ethnicities.White Alone                                       2994 non-null   float64
 16  Ethnicities.White Alone	 not Hispanic or Latino               2994 non-null   float64
 17  Housing.Homeownership Rate                                    2994 non-null   float64
 18  Housing.Households                                            2994 non-null   float64
 19  Housing.Housing Units                                         2994 non-null   float64
 20  Housing.Median Value of Owner-Occupied Units                  2994 non-null   float64
 21  Housing.Persons per Household                                 2994 non-null   float64
 22  Income.Median Houseold Income                                 2994 non-null   int64
 23  Income.Per Capita Income                                      2994 non-null   int64
 24  Miscellaneous.Foreign Born                                    2994 non-null   float64
 25  Miscellaneous.Land Area                                       2994 non-null   float64
 26  Miscellaneous.Language Other than English at Home             2994 non-null   float64
 27  Miscellaneous.Living in Same House +1 Years                   2994 non-null   float64
 28  Miscellaneous.Manufacturers Shipments                         2994 non-null   float64
 29  Miscellaneous.Mean Travel Time to Work                        2994 non-null   float64
 30  Miscellaneous.Percent Female                                  2994 non-null   float64
 31  Miscellaneous.Veterans                                        2994 non-null   float64
 32  Population.2020 Population                                    2994 non-null   int64
 33  Population.2010 Population                                    2994 non-null   int64
 34  Population.Population per Square Mile                         2994 non-null   float64
 35  Sales.Accommodation and Food Services Sales                   2994 non-null   float64
 36  Sales.Retail Sales                                            2994 non-null   float64
 37  Employment.Firms.Total                                        2994 non-null   int64
 38  Employment.Firms.Women-Owned                                  2994 non-null   int64
 39  Employment.Firms.Men-Owned                                    2994 non-null   int64
 40  Employment.Firms.Minority-Owned                               2994 non-null   float64
 41  Employment.Firms.Nonminority-Owned                            2994 non-null   int64
 42  Employment.Firms.Veteran-Owned                                2994 non-null   int64
 43  Employment.Firms.Nonveteran-Owned                             2994 non-null   int64
dtypes: float64(31), int64(10), object(3)
memory usage: 1.0+ MB

#Data Merging
Find the common keys in the two dataframes and put it into a list

In [ ]:

common_keys = list(set(mode_food_df['mergedkeycol']) & set(county_df['mergedkeycol'])) # & means intersection
print(len(common_keys))
print("Common keys between the two data frames: " + str(common_keys))

# don't want duplicate county and state columns after merging
county_df_cols_to_keep = [col for col in county_df.columns if col not in ['County', 'State']]
county_df_to_merge = county_df[county_df_cols_to_keep]

merged_df = pd.merge(mode_food_df, county_df_to_merge, on='mergedkeycol', how='inner')
merged_df

2993

,County,Population,State,mergedkeycol,Housing Data.Residing in Group Quarters,Housing Data.Total Housing Units,Vehicle Access.1 Mile,Vehicle Access.1/2 Mile,Vehicle Access.10 Miles,Vehicle Access.20 Miles,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,autaugacounty,54571,al,autaugacountyal,455,20221,834,1045,222.0,0,...,91.8,93431.0,607854.0,2949,1093,1499,616.0,2160,285,2401
1,baldwincounty,182265,al,baldwincountyal,2307,73180,1653,2178,32.0,0,...,114.6,560602.0,3145789.0,19732,6505,10935,2130.0,16893,2364,16183
2,barbourcounty,27457,al,barbourcountyal,3193,9820,545,742,201.0,0,...,31.0,26157.0,206477.0,1687,760,755,657.0,941,147,1445
3,bibbcounty,22915,al,bibbcountyal,2224,7953,312,441,0.0,0,...,36.8,10136.0,118871.0,1310,254,958,205.0,1050,288,967
4,blountcounty,57322,al,blountcountyal,489,21578,752,822,0.0,0,...,88.9,27146.0,298745.0,4550,1400,2746,368.0,4011,353,4030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2988,sweetwatercounty,43806,wy,sweetwatercountywy,679,16475,284,372,18.0,13,...,4.2,128948.0,921443.0,3473,908,1755,364.0,2891,307,2890
2989,tetoncounty,21294,wy,tetoncountywy,271,8973,74,144,0.0,0,...,5.3,343991.0,512610.0,6235,1989,3000,334.0,5493,447,5362
2990,uintacounty,21118,wy,uintacountywy,270,7668,175,283,9.0,0,...,10.1,35485.0,389868.0,2008,519,919,113.0,1801,213,1651
2991,washakiecounty,8533,wy,washakiecountywy,140,3492,37,106,7.0,6,...,3.8,11642.0,95392.0,847,258,328,71.0,727,76,685
2992,westoncounty,7208,wy,westoncountywy,313,3021,22,43,2.0,0,...,3.0,9392.0,76514.0,742,197,323,0.0,693,184,508

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2993 entries, 0 to 2992
Data columns (total 67 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   County                                                        2993 non-null   object
 1   Population                                                    2993 non-null   object
 2   State                                                         2993 non-null   object
 3   mergedkeycol                                                  2993 non-null   object
 4   Housing Data.Residing in Group Quarters                       2993 non-null   int64
 5   Housing Data.Total Housing Units                              2993 non-null   int64
 6   Vehicle Access.1 Mile                                         2993 non-null   int64
 7   Vehicle Access.1/2 Mile                                       2993 non-null   int64
 8   Vehicle Access.10 Miles                                       2993 non-null   float64
 9   Vehicle Access.20 Miles                                       2993 non-null   int64
 10  Low Access Numbers.Children.1 Mile                            2993 non-null   int64
 11  Low Access Numbers.Children.1/2 Mile                          2993 non-null   int64
 12  Low Access Numbers.Children.10 Miles                          2993 non-null   int64
 13  Low Access Numbers.Children.20 Miles                          2993 non-null   int64
 14  Low Access Numbers.Low Income People.1 Mile                   2993 non-null   int64
 15  Low Access Numbers.Low Income People.1/2 Mile                 2993 non-null   int64
 16  Low Access Numbers.Low Income People.10 Miles                 2993 non-null   int64
 17  Low Access Numbers.Low Income People.20 Miles                 2993 non-null   int64
 18  Low Access Numbers.People.1 Mile                              2993 non-null   float64
 19  Low Access Numbers.People.1/2 Mile                            2993 non-null   int64
 20  Low Access Numbers.People.10 Miles                            2993 non-null   int64
 21  Low Access Numbers.People.20 Miles                            2993 non-null   int64
 22  Low Access Numbers.Seniors.1 Mile                             2993 non-null   int64
 23  Low Access Numbers.Seniors.1/2 Mile                           2993 non-null   float64
 24  Low Access Numbers.Seniors.10 Miles                           2993 non-null   int64
 25  Low Access Numbers.Seniors.20 Miles                           2993 non-null   int64
 26  Age.Percent 65 and Older                                      2993 non-null   float64
 27  Age.Percent Under 18 Years                                    2993 non-null   float64
 28  Age.Percent Under 5 Years                                     2993 non-null   float64
 29  Education.Bachelor's Degree or Higher                         2993 non-null   float64
 30  Education.High School or Higher                               2993 non-null   float64
 31  Employment.Nonemployer Establishments                         2993 non-null   float64
 32  Ethnicities.American Indian and Alaska Native Alone           2993 non-null   float64
 33  Ethnicities.Asian Alone                                       2993 non-null   float64
 34  Ethnicities.Black Alone                                       2993 non-null   float64
 35  Ethnicities.Hispanic or Latino                                2993 non-null   float64
 36  Ethnicities.Native Hawaiian and Other Pacific Islander Alone  2993 non-null   float64
 37  Ethnicities.Two or More Races                                 2993 non-null   float64
 38  Ethnicities.White Alone                                       2993 non-null   float64
 39  Ethnicities.White Alone	 not Hispanic or Latino               2993 non-null   float64
 40  Housing.Homeownership Rate                                    2993 non-null   float64
 41  Housing.Households                                            2993 non-null   float64
 42  Housing.Housing Units                                         2993 non-null   float64
 43  Housing.Median Value of Owner-Occupied Units                  2993 non-null   float64
 44  Housing.Persons per Household                                 2993 non-null   float64
 45  Income.Median Houseold Income                                 2993 non-null   int64
 46  Income.Per Capita Income                                      2993 non-null   int64
 47  Miscellaneous.Foreign Born                                    2993 non-null   float64
 48  Miscellaneous.Land Area                                       2993 non-null   float64
 49  Miscellaneous.Language Other than English at Home             2993 non-null   float64
 50  Miscellaneous.Living in Same House +1 Years                   2993 non-null   float64
 51  Miscellaneous.Manufacturers Shipments                         2993 non-null   float64
 52  Miscellaneous.Mean Travel Time to Work                        2993 non-null   float64
 53  Miscellaneous.Percent Female                                  2993 non-null   float64
 54  Miscellaneous.Veterans                                        2993 non-null   float64
 55  Population.2020 Population                                    2993 non-null   int64
 56  Population.2010 Population                                    2993 non-null   int64
 57  Population.Population per Square Mile                         2993 non-null   float64
 58  Sales.Accommodation and Food Services Sales                   2993 non-null   float64
 59  Sales.Retail Sales                                            2993 non-null   float64
 60  Employment.Firms.Total                                        2993 non-null   int64
 61  Employment.Firms.Women-Owned                                  2993 non-null   int64
 62  Employment.Firms.Men-Owned                                    2993 non-null   int64
 63  Employment.Firms.Minority-Owned                               2993 non-null   float64
 64  Employment.Firms.Nonminority-Owned                            2993 non-null   int64
 65  Employment.Firms.Veteran-Owned                                2993 non-null   int64
 66  Employment.Firms.Nonveteran-Owned                             2993 non-null   int64
dtypes: float64(34), int64(29), object(4)
memory usage: 1.5+ MB